services:
  postgres:
    image: postgres:17
    container_name: postgres_ecommerce
    restart: unless-stopped
    environment:
      POSTGRES_USER: nguyenhuynhsang
      POSTGRES_PASSWORD: nguyenhuynhsang
      POSTGRES_DB: Ecommerce
    ports:
      - "5002:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nguyenhuynhsang"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:

networks:
  backend:
    driver: bridge
